interface PageSEO {
  path: string;
  title: string;
  description: string;
  keywords: string[];
  priority: number;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  noindex?: boolean;
  schemaType?: string;
  ogImage?: string;
}

// Моделюємо SEO_CONFIG як порожній об'єкт для TypeScript
import { SITE_INFO } from '../../utils/constants';

interface RobotsConfig {
  userAgents: string[];
  allow: string[];
  disallow: string[];
  sitemapUrl: string;
  crawlDelay?: number;
  host?: string;
}

/**
 * Конфігурація robots.txt
 */
export const getRobotsConfig = (): RobotsConfig => {
  // Сторінки, які не треба індексувати
  const noindexPages: string[] = []; // Початкове значення
  
  // Якщо вам потрібно реально використовувати SEO_CONFIG, вам потрібно буде його імпортувати
  // Для зараз залишимо порожній масив
  // const noindexPages = Object.values(SEO_CONFIG)
  //   .filter((page: PageSEO) => page.noindex)
  //   .map(page => page.path);

  return {
    userAgents: ['*', 'Googlebot', 'BingBot', 'Slurp', 'DuckDuckBot', 'Baiduspider', 'Yandex'],
    allow: ['/'],
    disallow: [
      '/admin',
      '/private',
      '/client-portal',
      ...noindexPages.filter(path => !path.startsWith('/legal'))
    ],
    sitemapUrl: `${SITE_INFO.url}/sitemap.xml`,
    crawlDelay: 1, // 1 секунда затримки
    host: SITE_INFO.url?.replace('https://', '')
  };
};

/**
 * Генерує вміст robots.txt
 */
export const generateRobotsTxt = (config?: Partial<RobotsConfig>): string => {
  const defaultConfig = getRobotsConfig();
  const finalConfig = { ...defaultConfig, ...config };
  
  let robotsContent = '';
  
  // Основний user-agent
  robotsContent += `User-agent: *\n`;
  finalConfig.disallow.forEach(path => {
    robotsContent += `Disallow: ${path}\n`;
  });
  
  // Спеціальні налаштування для пошукових систем
  robotsContent += `\n# Google\n`;
  robotsContent += `User-agent: Googlebot\n`;
  robotsContent += `Allow: /\n`;
  if (finalConfig.crawlDelay) {
    robotsContent += `Crawl-delay: ${finalConfig.crawlDelay}\n`;
  }
  
  robotsContent += `\n# Bing\n`;
  robotsContent += `User-agent: Bingbot\n`;
  robotsContent += `Allow: /\n`;
  
  // Host директиву (для Yandex)
  if (finalConfig.host) {
    robotsContent += `\n# Yandex\n`;
    robotsContent += `Host: ${finalConfig.host}\n`;
  }
  
  // Sitemap
  robotsContent += `\n# Sitemap\n`;
  robotsContent += `Sitemap: ${finalConfig.sitemapUrl}\n`;
  
  // Додаткові sitemaps якщо є
  robotsContent += `Sitemap: ${SITE_INFO.url}/sitemap-index.xml\n`;
  
  // Коментарі
  robotsContent += `\n# Generated by WebStart Studio SEO Utils\n`;
  robotsContent += `# Last updated: ${new Date().toISOString()}\n`;
  
  return robotsContent;
};

/**
 * Створює robots.txt файл (використовувати тільки в Node.js середовищі)
 */
export const createRobotsFile = (config?: Partial<RobotsConfig>): void => {
  if (typeof window === 'undefined' && process.env.NODE_ENV === 'production') {
    try {
      // Використовуємо динамічний імпорт для Node.js модулів
      import('fs').then(fs => {
        import('path').then(path => {
          const robotsContent = generateRobotsTxt(config);
          const publicPath = path.join(process.cwd(), 'public', 'robots.txt');
          
          fs.writeFileSync(publicPath, robotsContent, 'utf8');
          console.log('✅ Robots.txt згенеровано у public/robots.txt');
        });
      }).catch(error => {
        console.error('Помилка при створенні robots.txt:', error);
      });
    } catch (error) {
      console.error('Помилка при створенні robots.txt:', error);
    }
  }
};

/**
 * Генерує robots meta теги для HTML
 */
export const generateRobotsMeta = (pageSEO: PageSEO): string => {
  if (pageSEO.noindex) {
    return 'noindex, nofollow';
  }
  
  // За замовчуванням дозволяємо все
  let directives = 'index, follow';
  
  // Додаємо додаткові директиви
  if (pageSEO.priority < 0.3) {
    directives += ', noarchive';
  }
  
  // Для старих сторінок
  const pageAge = new Date().getFullYear() - 2023; // Приклад
  if (pageAge > 2) {
    directives += ', noimageindex';
  }
  
  return directives;
};

/**
 * Перевіряє правильність robots.txt
 */
export const validateRobotsTxt = (content: string): {
  isValid: boolean;
  warnings: string[];
  errors: string[];
} => {
  const warnings: string[] = [];
  const errors: string[] = [];
  
  // Базова перевірка
  if (!content.includes('User-agent:')) {
    errors.push('Відсутній User-agent directive');
  }
  
  if (!content.includes('Sitemap:')) {
    warnings.push('Відсутня Sitemap directive');
  }
  
  // Перевірка на заборонені правила
  if (content.includes('Disallow: /')) {
    warnings.push('Заборонено весь сайт (Disallow: /) - перевірте');
  }
  
  // Перевірка на наявність важливих сторінок
  const importantPages = ['/', '/services', '/contact'];
  importantPages.forEach(page => {
    if (content.includes(`Disallow: ${page}`)) {
      errors.push(`Заборонено важливу сторінку: ${page}`);
    }
  });
  
  return {
    isValid: errors.length === 0,
    warnings,
    errors
  };
};